# Generated by Django 4.1 on 2023-03-03 20:11

from django.db import migrations, models
import froggr.models


class Migration(migrations.Migration):

    dependencies = [
        ('froggr', '0002_userprofile_alter_blogpost_user_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, upload_to=froggr.models.post_dir_path),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='text',
            field=models.TextField(default='My Frogg'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to=froggr.models.user_dir_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='text',
            field=models.TextField(default='My Profile.'),
        ),
    ]
