# Generated by Django 4.1 on 2023-03-03 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('froggr', '0003_blogpost_image_blogpost_text_userprofile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
