# Generated by Django 4.1 on 2023-03-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froggr', '0004_alter_connection_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
        migrations.AddConstraint(
            model_name='blogpost',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='only 1 blog with a title per user'),
        ),
    ]
