# Generated by Django 4.1 on 2023-03-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froggr', '0005_rename_content_comment_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='reacton',
            new_name='reaction',
        ),
    ]
