# Generated by Django 4.1 on 2023-03-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froggr', '0014_alter_blogpost_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
