# Generated by Django 4.1 on 2023-03-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froggr', '0015_blogpost_score'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='blogpost',
            name='only 1 blog with a title per user',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
