# Generated by Django 2.2.26 on 2023-03-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froggr', '0017_auto_20230314_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
