# Generated by Django 2.2.26 on 2023-03-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froggr', '0019_alter_blogpost_id_alter_comment_id_and_more'),
        ('froggr', '0016_remove_blogpost_only 1 blog with a title per user_and_more'),
    ]

    operations = [
    ]
