# Generated by Django 4.1 on 2023-03-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froggr', '0020_merge_20230318_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
    ]
