# Generated by Django 2.2.26 on 2023-03-19 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('froggr', '0022_auto_20230318_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='users_liked',
            field=models.ManyToManyField(blank=True, related_name='posts_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
