# Generated by Django 4.1 on 2023-03-20 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froggr', '0023_alter_blogpost_id_alter_comment_id_and_more'),
        ('froggr', '0023_blogpost_users_liked'),
    ]

    operations = [
    ]
