# Generated by Django 4.1 on 2023-03-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froggr', '0029_alter_blogpost_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
